### ISSUE TITLE
有错误怎么解决

### ISSUE THREAD

**Issue by Gx952743985** [yulingtianxia/FishChat#1]
#import <CaptainHook/CaptainHook.h> 缺少这个库

**Comment by yulingtianxia** [comment]
@Gx952743985 你需要安装 iOSOpenDev 或 theos

**Comment by Gx952743985** [comment]
手机需要越狱么? 还有就是我这个图标是怎么了
![83c38a45-9d85-40b7-a231-c614ca027aef](https://cloud.githubusercontent.com/assets/16395032/23577996/5e3fab3e-0107-11e7-883c-bb34b63719d4.png)

**Comment by yulingtianxia** [comment]
@Gx952743985 先仔细看文章吧

**Comment by Nododo** [comment]
hi
针对 “ 你需要安装 iOSOpenDev 或 theos”
是或还是和？ 我安装了theos 还是提示同样的问题
