### ISSUE TITLE
想知道这个self指向哪个对象

### ISSUE THREAD

**Issue by ycace** [yulingtianxia/FishChat#11]
![image](https://user-images.githubusercontent.com/12710515/28910768-c7dfb37e-7860-11e7-9999-4a11a7b1d5df.png)
新手问题，还请谅解。

**Comment by yulingtianxia** [comment]
@ycace 被 Hook 的类的实例

**Comment by ycace** [comment]
但是该代码块从没有传入self实例对象，我用的时候出现了如下错误，没有理解，还望指导
![image](https://user-images.githubusercontent.com/12710515/28954142-966c9c76-790f-11e7-853c-506a77d9438c.png)

**Comment by iOSleep** [comment]
@ycace mrc的不会有这个提示, 说明你是arc的

**Comment by ycace** [comment]
Thanks!
