### ISSUE TITLE
新建项目使用CH（CHDeclareMethod0）使用self关键字无法通过编译

### ISSUE THREAD

**Issue by huakucha** [yulingtianxia/FishChat#13]
CHDeclareClass(NewSettingViewController) 
CHDeclareMethod0(void, NewSettingViewController, reloadTableData)
{
    CHSuper0(NewSettingViewController, reloadTableData);
    MMTableViewInfo *tableInfo = [self valueForKeyPath:@"m_tableViewInfo"];
    
}
新建项目 编译不通过提示：Receiver type 'NewSettingViewController' for instance message is a forward declaration 好像只要使用self就无法编译成功

**Comment by yulingtianxia** [comment]
@huakucha 请使用 mrc
