### ISSUE TITLE
需要一个6.5.5版本的wechat.ipa

### ISSUE THREAD

**Issue by shippomx** [yulingtianxia/FishChat#14]
现在安装的6.5.14版本通过这个方法安装后，还是看不到任何添加的功能  蟹蟹啦

**Comment by yulingtianxia** [comment]
@shippomx 我刚试过6.5.14，OK 的

**Comment by luohui8891** [comment]
@yulingtianxia 为什么我砸开看不到方法，而是一些奇怪代码（看截图）。但是我砸开其他的APP是可以看到方法的。
<img src="https://user-images.githubusercontent.com/1223339/29367994-15d45ef2-82d1-11e7-826b-523b5743cee0.png" alt="" width="600">
