### ISSUE TITLE
你这个sb间接的助纣为虐

### ISSUE THREAD

**Issue by liangzhixin** [yulingtianxia/FishChat#30]

**Comment by liangzhixin** [comment]
你这个sb间接的助纣为虐 #30

**Comment by Naville** [comment]
中专生黑产气急败坏的样子可太好笑了

**Comment by liangzhixin** [comment]
这不是我发的啊，什么鬼

**Comment by liangzhixin** [comment]
为什么这些骂人的评论我都没发过，但是我看见好几条了，这是被盗号了？

**Comment by ZeroAurora** [comment]
…不予置评，如果被盗了赶紧改密码，如果是装的自己心里清楚

**Comment by liangzhixin** [comment]
不是啊，我都没浏览过这个东西，不知道为啥我仓库里会有这个别人的仓库，还有这些评论，现在我删都删不了这个仓库

**Comment by ZeroAurora** [comment]
既然这样，close 所有的 issues，修改密码，发表声明，是最好的办法了（

**Comment by liangzhixin** [comment]
为什么我仓库里会有别人的仓库呢，一直显示在我的仓库里，删也不知道怎么删，求教啊

**Comment by ZeroAurora** [comment]
你原来有 star 的项目吗？为什么我看你一个 star 都没有

**Comment by liangzhixin** [comment]
原来好像有，刚我好像点了unstar啥的

**Comment by ZeroAurora** [comment]
fork 的项目可以进 repo 的 setting 里删

**Comment by liangzhixin** [comment]
就是主页面那里，不知道为啥一直显示。。。。

**Comment by ZeroAurora** [comment]
把这几个 issues 赶紧 close 掉再说

**Comment by liangzhixin** [comment]
怎么close啊、、、不懂啊，只会添加仓库啥的

**Comment by ZeroAurora** [comment]
在回复框底下，发送按钮旁边

**Comment by ZeroAurora** [comment]
初学者？参加了培训机构？会不会是这方面的猫腻

**Comment by liangzhixin** [comment]
正儿八经的应届毕业生啊，没参加过啊，我看了下评论时间，还是昨天发的，真tm神奇了，不过还是谢谢你啊

**Comment by ZeroAurora** [comment]
具体起因见 https://github.com/yulingtianxia/FuckFakeGitHubStars 和 https://m.weibo.cn/status/4290447641595947

**Comment by ghost** [comment]
@liangzhixin 请在 https://github.com/settings/security 检查是否有异常的登录记录，并修改密码。

**Comment by liangzhixin** [comment]
wk，我想起来了，我的项目配置里有我的github密码，sb了，但是他们怎么会细看我这么一个初学者的代码呢

**Comment by liangzhixin** [comment]
确实有别人登录的记录，密码我已经改了，谢谢各位了，多谢

**Comment by liangzhixin** [comment]
@yulingtianxia 账号被盗了，密码已经修改。非常抱歉，sorry

**Comment by ZeroAurora** [comment]
项目里的 token 和密码一类的最好留空，全部用环境变量吧

**Comment by liangzhixin** [comment]
好的，多谢提醒
