### ISSUE TITLE
请问您的砸壳安装包是在哪个助手下的呀？我从 PP 助手和爱思助手上下载的 6.5.7 越狱安装包安装后都直接闪退.

### ISSUE THREAD

**Issue by CrazyBunQnQ** [yulingtianxia/FishChat#4]
我没有修改项目逻辑，只改了脚本前三行的路径，脚本执行如图：
![脚本执行结果](http://wx2.sinaimg.cn/mw690/a6e9cb00ly1fenb5snhn3j214a1doarl.jpg)

**Comment by yulingtianxia** [comment]
我觉得 OK
